/**
 * Sample CEU products and bundles data
 * Based on CEUniverse structure for Pacific ABA Academy
 */

export const sampleProducts = [
  // New Modules
  {
    name: "B.F. Skinner on Behaviorism and Verbal Behavior",
    description: "An in-depth exploration of B.F. Skinner's foundational work on behaviorism and verbal behavior, essential for understanding ABA principles.",
    format: "Interactive Video",
    category: "General",
    ceuCredits: 2,
    ethicsCredits: 0,
    supervisionCredits: 0,
    price: 16.99,
    originalPrice: 19.99,
    instructor: "B.F. Skinner & Eve Segal",
    rating: 4.75,
    reviewCount: 4,
  },
  {
    name: "When Science Meets Animal Training: An Interview with Bob Bailey",
    description: "A fascinating interview with renowned animal trainer Bob Bailey discussing the intersection of science and practical animal training.",
    format: "Interactive Video",
    category: "General",
    ceuCredits: 0.5,
    ethicsCredits: 0,
    supervisionCredits: 0,
    price: 4.24,
    originalPrice: 4.99,
    instructor: "Bob Bailey",
    rating: 4.0,
    reviewCount: 1,
  },
  {
    name: "Demonstration of Parent Training to Address Early Self-Injury in Young Children with Delays",
    description: "A practical demonstration of evidence-based parent training techniques for addressing self-injurious behavior in young children.",
    format: "Article Quiz",
    category: "General",
    ceuCredits: 1,
    ethicsCredits: 0,
    supervisionCredits: 0,
    price: 8.49,
    originalPrice: 9.99,
    instructor: "Jill Fodstad, Alexandra Kirsch, Micah Faidley, & Nerissa Bauer",
    rating: 4.5,
    reviewCount: 8,
  },
  {
    name: "How to Identify Ethical Practices in Organizations Prior to Employment",
    description: "Learn how to evaluate organizational ethics and identify ethical practices before accepting employment in ABA settings.",
    format: "Article Quiz",
    category: "Ethics",
    ceuCredits: 1,
    ethicsCredits: 1,
    supervisionCredits: 0,
    price: 8.49,
    originalPrice: 9.99,
    instructor: "Matthew Brodhead, Shawn Quigley, & David Cox",
    rating: 5.0,
    reviewCount: 4,
  },

  // Bestsellers
  {
    name: "An Introduction to Relational Frame Theory (RFT)",
    description: "Comprehensive introduction to Relational Frame Theory, a cutting-edge theoretical framework for understanding human language and cognition in ABA.",
    format: "Multimedia Tutorial",
    category: "General",
    ceuCredits: 7,
    ethicsCredits: 0,
    supervisionCredits: 0,
    price: 59.49,
    originalPrice: 69.99,
    instructor: "Eric J. Fox",
    rating: 4.55,
    reviewCount: 504,
  },
  {
    name: "A Case Study in the Misrepresentation of Applied Behavior Analysis in Autism: The Gernsbacher Lectures",
    description: "Critical analysis of how ABA is sometimes misrepresented, featuring the Gernsbacher Lectures on accurate representation of ABA practices.",
    format: "Article Quiz",
    category: "Ethics",
    ceuCredits: 3.5,
    ethicsCredits: 3.5,
    supervisionCredits: 0,
    price: 29.74,
    originalPrice: 34.99,
    instructor: "Edward K. Morris",
    rating: 4.41,
    reviewCount: 59,
  },
  {
    name: "An Introduction to Verbal Behavior",
    description: "Foundational course on Skinner's theory of verbal behavior and its applications in ABA practice with autistic individuals.",
    format: "Multimedia Tutorial",
    category: "General",
    ceuCredits: 8,
    ethicsCredits: 0,
    supervisionCredits: 0,
    price: 67.99,
    originalPrice: 79.99,
    instructor: "Norman Peterson",
    rating: 4.24,
    reviewCount: 306,
  },
  {
    name: "Mastering the Basics of Visual Analysis",
    description: "Essential skills for conducting accurate visual analysis of behavioral data, a critical competency for BCBAs.",
    format: "Multimedia Tutorial",
    category: "General",
    ceuCredits: 2,
    ethicsCredits: 0,
    supervisionCredits: 0,
    price: 16.99,
    originalPrice: 19.99,
    instructor: "Katie Wolfe & Timothy A. Slocum",
    rating: 4.32,
    reviewCount: 128,
  },
  {
    name: "Supervision Best Practices for BCBA Supervisors",
    description: "Comprehensive guide to providing effective supervision as a BCBA, covering ethical considerations and practical strategies.",
    format: "Multimedia Tutorial",
    category: "Supervision",
    ceuCredits: 3,
    ethicsCredits: 0,
    supervisionCredits: 3,
    price: 29.99,
    originalPrice: 34.99,
    instructor: "Dr. Ramen Saggu",
    rating: 4.8,
    reviewCount: 42,
  },
  {
    name: "Ethical Decision-Making in Applied Behavior Analysis",
    description: "Deep dive into ethical frameworks and decision-making processes for BCBAs facing complex ethical dilemmas.",
    format: "Article Quiz",
    category: "Ethics",
    ceuCredits: 2,
    ethicsCredits: 2,
    supervisionCredits: 0,
    price: 16.99,
    originalPrice: 19.99,
    instructor: "Shawn Quigley",
    rating: 4.7,
    reviewCount: 67,
  },
];

export const sampleBundles = [
  {
    name: "Galactic Bundle – 32 BCBA CEUs (with Ethics & Supervision)",
    description: "Our most comprehensive bundle featuring 32 total CEUs including 4 ethics and 3 supervision CEUs. Perfect for BCBAs needing significant CEU hours.",
    bundleType: "Galactic",
    totalCeus: 32,
    ethicsCeus: 4,
    supervisionCeus: 3,
    price: 216.99,
    originalPrice: 319.86,
    productIds: [1, 2, 3, 4, 5, 6, 7, 8, 9], // Will be mapped to actual product IDs
  },
  {
    name: "Supernova Bundle – 20 BCBA CEUs (with Ethics & Supervision)",
    description: "A substantial bundle with 20 total CEUs including 4 ethics and 3 supervision CEUs. Great for mid-year CEU needs.",
    bundleType: "Supernova",
    totalCeus: 20,
    ethicsCeus: 4,
    supervisionCeus: 3,
    price: 139.89,
    originalPrice: 199.89,
    productIds: [1, 5, 6, 7, 8], // Will be mapped to actual product IDs
  },
  {
    name: "Planetary Bundle – 7 BCBA CEUs (with Ethics & Supervision)",
    description: "A focused bundle with 7 total CEUs including 4 ethics and 3 supervision CEUs. Ideal for quick CEU fulfillment.",
    bundleType: "Planetary",
    totalCeus: 7,
    ethicsCeus: 4,
    supervisionCeus: 3,
    price: 48.94,
    originalPrice: 69.94,
    productIds: [4, 8, 9], // Will be mapped to actual product IDs
  },
  {
    name: "Celestial Bundle – 15 BCBA CEUs",
    description: "A well-rounded bundle with 15 total CEUs focusing on core ABA competencies and professional development.",
    bundleType: "Custom",
    totalCeus: 15,
    ethicsCeus: 2,
    supervisionCeus: 1,
    price: 99.99,
    originalPrice: 129.99,
    productIds: [5, 6, 7, 8], // Will be mapped to actual product IDs
  },
];
